# Generated by Django 3.2.7 on 2021-11-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=320),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='Contact | Bake My Day Inquiry', max_length=254),
        ),
    ]
