# Generated by Django 3.2.7 on 2021-11-22 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20211122_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='Bake My Day Inquiry', max_length=254),
        ),
    ]
