# Generated by Django 3.2.7 on 2021-11-22 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contact_subject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactDetail',
        ),
    ]
