# Generated by Django 3.2.7 on 2021-11-22 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_rename_contact_contactdetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactDetail',
            new_name='ContactInquiry',
        ),
    ]
