# Generated by Django 3.2.7 on 2021-11-18 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211118_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='blog_preview',
        ),
    ]
