# Generated by Django 3.1.7 on 2021-04-09 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210409_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='has_flavour',
            new_name='has_flavours',
        ),
    ]
